-- Define your visual elements here
-- For examples, and a complete list on the possible elements and their 
-- properties, go to https://github.com/fisadev/conky-draw/
-- (and be sure to use the lastest version)
elements = {
{
    kind = 'bar_graph',
--    conky_value = 'exec nvidia-smi --query-gpu="utilization.gpu" --format=csv,noheader,nounits',
    conky_value = 'exec sudo /home/viktor/.i3/conky/get_amdgpu_load.sh',
    from = {x = 6, y = 20},
    to = {x = 6, y = 0},
    background_thickness = 8,
    bar_thickness = 8,
    bar_color = 0xFF5500,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu0',
    from = {x = 14, y = 20},
    to = {x = 14, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu1',
    from = {x = 19, y = 20},
    to = {x = 19, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu2',
    from = {x = 24, y = 20},
    to = {x = 24, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu3',
    from = {x = 29, y = 20},
    to = {x = 29, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu4',
    from = {x = 34, y = 20},
    to = {x = 34, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu5',
    from = {x = 39, y = 20},
    to = {x = 39, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu6',
    from = {x = 44, y = 20},
    to = {x = 44, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu7',
    from = {x = 49, y = 20},
    to = {x = 49, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu8',
    from = {x = 54, y = 20},
    to = {x = 54, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu9',
    from = {x = 59, y = 20},
    to = {x = 59, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu10',
    from = {x = 64, y = 20},
    to = {x = 64, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu11',
    from = {x = 69, y = 20},
    to = {x = 69, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x00BFFA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'memperc',
    from = {x = 77, y = 20},
    to = {x = 77, y = 0},
    background_thickness = 8,
    bar_thickness = 8,
    bar_color = 0x00FF55,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'swapperc',
    from = {x = 87, y = 20},
    to = {x = 87, y = 0},
    background_thickness = 8,
    bar_thickness = 8,
    bar_color = 0x00AAAA,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'exec iostat -dx /dev/nvme0n1 | awk \'/nvme0n1/ {print $16}\'',
    from = {x = 95, y = 20},
    to = {x = 95, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0xAAAA00,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'exec iostat -dx /dev/sda1 | awk \'/sda1/ {print $16}\'',
    from = {x = 100, y = 20},
    to = {x = 100, y = 0},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0xAAAA00,
    background_color = 0x555555,
},
--{
--    kind = 'bar_graph',
--    conky_value = 'exec iostat -dx /dev/sda | awk \'/^sda/ {print $16}\'',
--    from = {x = 75, y = 20},
--    to = {x = 75, y = 0},
--    background_thickness = 4,
--    bar_thickness = 4,
--    bar_color = 0xAAAA00,
--    background_color = 0x555555,
--},
--{
--    kind = 'bar_graph',
--    conky_value = 'exec iostat -dx /dev/sdb | awk \'/^sdb/ {print $16}\'',
--    from = {x = 80, y = 20},
--    to = {x = 80, y = 0},
--    background_thickness = 4,
--    bar_thickness = 4,
--    bar_color = 0xAAAA00,
--    background_color = 0x555555,
--},
}
